//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КВАНТ.Logical.Engine {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class modbus_setting : global::System.Configuration.ApplicationSettingsBase {
        
        private static modbus_setting defaultInstance = ((modbus_setting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new modbus_setting())));
        
        public static modbus_setting Default {
            get {
                return defaultInstance;
            }
        }
    }
}
